In [ ]:
from functools import wraps

def log_call(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        
        print(f"Calling {func.__name__} with args={args}, kwargs={kwargs}")
        
        result = func(*args, **kwargs)
        
        return result
    return wrapper

In [8]:
@log_call
def greet(name, age=None):
    if age:
        return f"Hello {name}, you are {age} years old"
    return f"Hello {name}"

In [9]:
greet("Nurudeen")

Calling greet with args=('Nurudeen',), kwargs={}


'Hello Nurudeen'

In [10]:
greet("Abdulsalaam", age=60)

Calling greet with args=('Abdulsalaam',), kwargs={'age': 60}


'Hello Abdulsalaam, you are 60 years old'

In [52]:
def implement(func):
    @wraps(func)
    def wrapper(name, *args):
        if args:
            return func(name, *args)
        return func(name, 1)
    return wrapper

In [53]:
@implement
def greet_n_times(name, *args):
    return f"Hello {name}" * int(args[0])

In [54]:
greet_n_times("Nurudeen", 3)

'Hello NurudeenHello NurudeenHello Nurudeen'

In [1]:
DEFAULTS = {
    "host": "localhost",
    "port": 8080,
    "debug": False,
    "timeout": 30,
}


In [2]:
def build_config(**overrides):
    return {**DEFAULTS, **overrides}

In [3]:
new_dict = build_config(port=9090, debug=True)
print(new_dict)

{'host': 'localhost', 'port': 9090, 'debug': True, 'timeout': 30}


In [2]:
import numpy as np

In [14]:
num = np.arange(64).reshape(8,8)
num

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [ ]:
# [start:stop:step]
# num[row_index, col_index]

num[::2, 1::2]

array([[ 1,  3,  5,  7],
       [17, 19, 21, 23],
       [33, 35, 37, 39],
       [49, 51, 53, 55]])

In [39]:
num[[2,3,3],[0,3,-4]]

array([16, 27, 28])